[package]
name = "rust_task"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
ume86 = { path = "../lib/ume86" }
hrb = { path = "../lib/hrb" }
tek = { path = "../lib/tek" }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
codegen-units = 1

[package.metadata.wasm-bindgen]
wasm-module = false
