/**
 * rustTask.worker.ts
 * 
 * Worker thread for running Rust(WASM) tasks
 * Manages WASM initialization, environment setup, and execution
 * 
 * Design reference: Section 14 (Rust/Wasm インターフェース設計) in design.md
 */

import { applyFileSystemChanges, createTaskFileSystem } from './fs/taskFileSystem';
import type {
    FileSystemChangeMessage,
    KeyMessage,
    MainToWorkerMessage,
    WindowCloseMessage,
    WorkerCommand,
    WorkerStartMessage,
} from './protocol';
import { initHost } from './wasm/env';
import type { HostState } from './wasm/env';

/**
 * Worker state, shared with the WASM host functions in wasm/env.ts
 */
let workerState: HostState | null = null;

/**
 * WASM module of the running task, null while no task accepts events
 */
let rustTask: typeof import('./wasm/rust_task') | null = null;

/**
 * Send message to main thread
 */
const post = (message: WorkerCommand): void => {
    self.postMessage(message);
};

/**
 * Send text output to the terminal of this task
 * (設計書 14.3: println with newline)
 */
const println = (text: string): void => {
    post({ type: 'println', text });
};

/**
 * Wait for the specified time in milliseconds
 */
const sleep = (ms: number): Promise<void> => {
    return new Promise(resolve => setTimeout(resolve, ms));
};

const yieldChannel = new MessageChannel();

/**
 * Let pending messages from main thread be handled, then continue without delay
 * (nested setTimeout(0) would wait at least 4ms each time)
 */
const yieldToEventLoop = (): Promise<void> => {
    return new Promise(resolve => {
        yieldChannel.port1.onmessage = () => resolve();
        yieldChannel.port2.postMessage(null);
    });
};

/**
 * Handle key message from main thread
 * Enqueues the key to the event queue of the Rust task
 */
const handleKey = (message: KeyMessage): void => {
    if (!rustTask) {
        console.warn('[worker] Task is not running');
        return;
    }
    rustTask.push_key(message.code);
};

/**
 * Handle window close message from main thread
 * Forgets the window, so that the task's later operations on it are not sent to main thread.
 * Main thread decides whether the task ends when its windows are gone.
 */
const handleWindowClose = (message: WindowCloseMessage): void => {
    if (!workerState) {
        return;
    }

    // The window is already forgotten if the task closed it by itself
    for (const [numericWindowId, windowUuid] of workerState.windowIdMap.entries()) {
        if (windowUuid === message.windowId) {
            workerState.windowIdMap.delete(numericWindowId);
            break;
        }
    }
};

/**
 * Handle file system change from main thread
 * Applies it to the Worker's copy of the file system
 */
const handleFileSystemChange = (message: FileSystemChangeMessage): void => {
    if (!workerState) {
        return;
    }
    applyFileSystemChanges(workerState.fileSystem, message.changes);
};

/**
 * Handle task start request from main thread
 * Loads the WASM module and runs the task until it exits
 */
const runTask = async (startData: WorkerStartMessage): Promise<void> => {
    // console.log('[worker] Received startWithCommand message');

    try {
        // 1. Initialize worker state
        const fileSystem = createTaskFileSystem(startData.fileSystemSnapshot);

        workerState = {
            fileSystem,
            windowIdMap: new Map(),
            nextWindowId: 0,
            initTime: performance.now(),
        };

        // 2. Register the state for the host functions that Rust/WASM calls
        // (rust_task.js imports them from the 'env' module, which is wasm/env.ts)
        initHost(workerState);

        // 3. Load and initialize WASM module
        // (generated by wasm-bindgen)
        // console.log('[worker] Loading WASM module...');
        let RustTask: typeof import('./wasm/rust_task');
        try {
            RustTask = await import('./wasm/rust_task');
            // console.log('[worker] WASM module loaded successfully');
        } catch (loadError) {
            const loadMsg = loadError instanceof Error ? loadError.message : String(loadError);
            console.error('[worker] Failed to load WASM module:', loadError);
            throw new Error(`WASM module load failed: ${loadMsg}`);
        }

        // Initialize WASM runtime
        try {
            if (typeof RustTask.default === 'function') {
                // console.log('[worker] Initializing WASM runtime...');
                await RustTask.default();
                // console.log('[worker] WASM runtime initialized successfully');
            } else {
                console.warn('[worker] RustTask.default is not a function');
            }
        } catch (initError) {
            const initMsg = initError instanceof Error ? initError.message : String(initError);
            console.error('[worker] Failed to initialize WASM runtime:', initError);
            throw new Error(`WASM initialization failed: ${initMsg}`);
        }

        // 4. Execute Rust task with parameters
        // (設計書 14.1: run_task is the main entry point)
        try {
            // console.log('[worker] Starting Rust task execution...');
            RustTask.run_task(startData.fileName, startData.commandLine);
        } catch (execError) {
            const execMsg = execError instanceof Error ? execError.message : String(execError);
            console.error('[worker] Rust task execution failed:', execError);
            throw new Error(`Task execution failed: ${execMsg}`);
        }

        // From here on the task accepts key events
        rustTask = RustTask;

        while (true) {
            const waitMs = RustTask.step();
            if (waitMs === undefined) {
                break;
            }
            if (waitMs > 0) {
                await sleep(waitMs);
            } else {
                await yieldToEventLoop();
            }
        }

        // 5. Signal completion
        // println('[worker] Task completed successfully');
        post({ type: 'done' });
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        const stack = error instanceof Error ? error.stack : '';

        // Log to console for visibility in all browsers
        console.error('[worker] Execution error:', error);
        console.error('[worker] Stack trace:', stack);

        // Send error output to terminal
        println(`[worker] Error: ${message}`);
        // if (stack) {
        //     println(`[worker] Stack: ${stack}`);
        // }

        post({
            type: 'error',
            message,
            stack,
        });
    } finally {
        // Clean up worker state
        rustTask = null;
        workerState = null;
        initHost(null);
    }
};

/**
 * Main message handler
 */
self.addEventListener('message', (event: MessageEvent<MainToWorkerMessage>) => {
    const message = event.data;
    switch (message.type) {
        case 'startWithCommand':
            void runTask(message);
            return;
        case 'key':
            handleKey(message);
            return;
        case 'windowClose':
            handleWindowClose(message);
            return;
        case 'fileSystemChanged':
            handleFileSystemChange(message);
            return;
    }
});
